In [2]:
import yfinance as yf

In [5]:
data = yf.download("002466.SZ", start="2020-01-01", end="2020-12-31")

[*********************100%***********************]  1 of 1 completed

In [6]:
data

Price       Adj Close      Close       High        Low       Open     Volume
Ticker      002466.SZ  002466.SZ  002466.SZ  002466.SZ  002466.SZ  002466.SZ
Date
2020-01-02  28.290262  30.690001  31.049999  29.400000  30.000000   56382010
2020-01-03  28.529930  30.950001  31.840000  29.639999  29.799999   81607942
2020-01-06  30.124657  32.680000  33.980000  31.129999  31.139999   91710971
2020-01-07  29.691406  32.209999  32.599998  31.719999  32.180000   59527130
2020-01-08  29.442518  31.940001  33.590000  31.400000  32.220001   72038080
...               ...        ...        ...        ...        ...        ...
2020-12-24  33.083656  35.889999  37.599998  35.410000  37.500000  134436792
2020-12-25  35.305214  38.299999  38.860001  35.000000  35.000000  122109942
2020-12-28  37.314754  40.480000  40.660000  37.299999  38.299999  140099589
2020-12-29  35.342083  38.340000  41.549999  37.410000  40.709999  146892259
2020-12-30  36.227016  39.299999  40.400002  38.560001  39.310001  110730615

[242 rows x 6 columns]